DELETE http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MjMzODYyMTIsInVzZXJJZCI6MX0.9KZZh_b09_WKRSIZdML1saP5WsPoYBnErjjmnaImffM