POST http://localhost:8080/events
content-type: application/json
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MjMzNTc5MzgsInVzZXJJZCI6MX0.y7sUteO6EDA3Wzm1aVxnbQZ9U-TlqVLZKeKCTg8GBQc

{
  "name": "Test event6",
  "description": "A test event6",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}