PUT http://localhost:8080/events/15
content-type: application/json

{
  "name": "Test event2",
  "description": "A test event2",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}